### ISSUE TITLE
Built-in idea

### ISSUE THREAD

**Issue by vihanb** [newbiedoodle/Esolangs#1]
the goat emoji outputs an ascii art goat. If the goat emoji is preceded by the text "down". the ascii-art goat is flipped

**Comment by newbiedoodle** [comment]
If you'd clicked the link, it would have automatically added the labels for you. Also, no.

**Comment by vihanb** [comment]
I did click the link

**Comment by newbiedoodle** [comment]
...Huh. I could've sworn the link worked. I guess not.
